CC = gcc

CFLAGS = -Wall -Wextra -O2 -Iinclude -pthread
LDLIBS = -lm -pthread -lpng

TARGET = mandelbrot

SRC = src/main.c \
      src/mandelbrot_core.c \
      src/mandelbrot_colour.c \
      src/mandelbrot_output.c

OBJ = $(SRC:.c=.o)

DATA_FILE = plot/mandel.dat
PLOT_SCRIPT = plot/mandel.gp
IMAGE_FILE = plot/mandel.png


# Default build
all: $(TARGET)


# Link executable
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET) $(LDLIBS)


# Compile source files
%.o: %.c include/mandelbrot.h
	$(CC) $(CFLAGS) -c $< -o $@


# Run Mandelbrot renderer
run: $(TARGET)
	./$(TARGET)


# Render Mandelbrot and generate PNG
render: $(TARGET)
	./$(TARGET)
	gnuplot $(PLOT_SCRIPT)


# Remove compiled files
clean:
	rm -f $(OBJ) $(TARGET)


# Remove generated render output
clean-render:
	rm -f $(DATA_FILE) $(IMAGE_FILE)


# Remove everything generated by the project
clean-all: clean clean-render


.PHONY: all run render clean clean-render clean-all
